### ISSUE TITLE
Option to copy SSH keys into authorized_keys from GitHub

### ISSUE THREAD

**Issue by rohankrishnadev** [robertdebock/ansible-role-users#12]
**Is your feature request related to a problem? Please describe.**
Listing all of the keys for multiple users seems a bit tiresome. We could, instead, copy the keys from GitHub to a users authorized_keys file.

**Describe the solution you'd like**
GitHub exposes the users public key at https://github.com/username.keys. If we could pass GitHub username as a variable then we can copy the keys over to the users authorized_keys file. I believe the authorized_keys module has provision for this (https://docs.ansible.com/ansible/latest/modules/authorized_key_module.html#examples)

**Describe alternatives you've considered**
Alternative is to list all the keys for the users, as we do now. 

**Additional context**
N/A

**Comment by robertdebock** [comment]
That's a cool feature indeed, thanks for the inspiration!

That would mean the `users_user_list` would need to be expanded with something like `authorized_keys_url`, or a boolean like `authorized_keys_from_github: true`.

So proposal 1 would be:
```yaml
---
    users_user_list:
      - name: someuser
        authorized_keys_url: "https://github.com/someuser.keys"
```

And proposal 2 would be:

```yaml
---
    users_user_list:
      - name: someuser
        authorized_keys_from_github: true
```

- 1 seems to be a little more flexible, it could take any URL.
- 2 requires the username (`someuser`) to be exactly the same in GitHub.

Please tell me if one of the two options would work for you.

**Comment by rohankrishnadev** [comment]
Thanks! I like the idea of the first one. As you mentioned it's more flexible. We'll need to skip some tasks like based on whether `authorized_keys_url` is set. E.g., [https://github.com/robertdebock/ansible-role-users/blob/8167face57ad87fc25d9575829f5a0f330663cad/tasks/user.yml#L110](https://github.com/robertdebock/ansible-role-users/blob/8167face57ad87fc25d9575829f5a0f330663cad/tasks/user.yml#L110) 

Also, it might be cleaner to add a separate task instead of modifying [https://github.com/robertdebock/ansible-role-users/blob/8167face57ad87fc25d9575829f5a0f330663cad/tasks/user.yml#L119](https://github.com/robertdebock/ansible-role-users/blob/8167face57ad87fc25d9575829f5a0f330663cad/tasks/user.yml#L119)

**Comment by robertdebock** [comment]
I read from the [authorized_key module](https://docs.ansible.com/ansible/latest/modules/authorized_key_module.html) that the `key` can already use pointing to a URL:

```text
= key
        The SSH public key(s), as a string or (since Ansible 1.9) url
        (https://github.com/username.keys).
```

So that would mean this should work:
```yaml
    users_user_list:
      - name: my_user
        authorized_keys:
          - "https://some.url/my_key.pub"
```

I'll update the tests and documentation, see if that works for you.
