### ISSUE TITLE
no test named 'boolean'

### ISSUE THREAD

**Issue by uqperryk** [robertdebock/ansible-role-users#18]
## Describe the bug

Using AWX 19.3.0 with this EE https://github.com/tomoliveri/ansible_aio_ee, and running this role returns an error:

template error while templating string: no test named 'boolean'

The role works fine for me normally, this is the first time I've tried to use the role in AWX however.

## Playbook

```yaml
---
- hosts: all
  become: yes
  become_user: root
  vars:
    users_user_list:
        <snip>    
  roles:
    - robertdebock.users
```

## Output

```
{
  "msg": "The conditional check 'users_cron_allow is boolean' failed. The error was: template error while templating string: no test named 'boolean'. String: {% if users_cron_allow is boolean %} True {% else %} False {% endif %}",
  "_ansible_no_log": false
}
```

## Environment

- Control node OS: AWX 19.3.0
- Ansible version: 2.11.6rc1.post0
- Managed node OS: Oracle Linux 8.4

Also, this looks to be a similar problem to here:  https://github.com/robertdebock/ansible-role-tomcat/issues/37
