### ISSUE TITLE
Option to copy public key or generate SSH keys only on instance

### ISSUE THREAD

**Issue by MLNW** [robertdebock/ansible-role-users#20]
## Proposed feature

Either add an option to copy the public key to the node or allow creation of SSH keys on the node itself.

## Rationale

When provisioning a new development machine I want to generate an SSH key on the machine which can be uploaded to GitLab/GitHub.

Currently, it is only possible to copy the private key to the machine but not both.
And in the end, I don't need the generated keys on the controller but on the node itself.

## Implementation option

The `ansible.builtin.user` module that is used has this option `generate_ssh_key: true` which would be enough for my needs.

**Comment by robertdebock** [comment]
There is now a way to copy a public key to a machine:

```yaml
users:
  - name: multiplekeys
    authorized_keys:
      - "ssh-rsa ABC1234"
      - "ssh-rsa ABC12345"
  - name: remotekey
    authorized_keys:
      # You can also download a public key from a URL.
      - "https://raw.githubusercontent.com/shaanr/smdb/master/file.pub"
```

Hope that helps!
