### ISSUE TITLE
Descriptions of more scary variable names

### ISSUE THREAD

**Issue by blaisep** [robertdebock/ansible-role-users#21]
## Proposed feature

Some of the variable names suggest (to me as N00B) that they might be risky. 
Can I add some descriptions, or a link to a main doc?

## Rationale

As a newcomer, I was about to install the minikube role and I noticed a reference to this role. It seems really cool and there is some ninja $#@! going on in the user settings which I would love to understand.

Perhaps there is a comprehensive doc somewhere. I could not immediately tell what module the `groups` variable related to. 

## Additional context

```
      users_user_list:
        - name: root                         # What if I already have a root account with a passwd ?
          cron_allow: yes
          unauthorized_keys:          # required? Is this a known-bad key?
            - "ssh-rsa ZYX54321"
        - name: blaise
          comment: Blaise Pabon
          uid: 1024
          group: blaise
          groups: users                  # how do I list more than one group? `users, wheel, libvirt` ? Also the word `groups` means something in Ansible...
          cron_allow: yes
          sudo_options: "ALL=(ALL) NOPASSWD: ALL"
          authorized_keys:
            - "ssh-rsa ABC123"
          expires: -1                                        # Does this mean the account never expires?
          password_validity_days: 9
        - name: notuser                               # Does this remove pre-existing users from the host?
          state: absent
```
and also:

```
        - name: remotekey                       # Who is Shaan and why do I add his key?
          authorized_keys:
            - "https://raw.githubusercontent.com/shaanr/smdb/master/file.pub"
        - name: systemuser
          system: yes
        - name: multisudo                       # This seems interesting, is this for a service account?
          sudo_options:
            - "ALL= NOPASSWD: /usr/bin/systemctl restart httpd"
            - "ALL= NOPASSWD: /usr/bin/systemctl start httpd"
```

Please consider [sponsoring me](https://github.com/sponsors/robertdebock).
