### ISSUE TITLE
ERROR! this task 'ansible.builtin.import_tasks' has extra params... when running playbook with the role

### ISSUE THREAD

**Issue by falkheiland** [robertdebock/ansible-role-users#22]
## Describe the bug

Error using the role in my playbook

## Playbook

playbook:
```yaml
---
- hosts: redacted

  tags:
    - user

  vars:
    ansible_user: "{{ base_user }}"
    ansible_password: "{{ base_user_password }}"
    ansible_sudo_pass: "{{ base_sudo_pass }}"

  become: true

  roles:
    - robertdebock.users

  tasks:
    - name: "Change password for {{ default_user }}"
      user:
        name: "{{ default_user }}"
        password: "{{ default_user_password | string | password_hash('sha512', 'A512') }}"

```
requirements.yml (excerpt)
```yaml
- src: robertdebock.users
  version: 5.4.0
```

```
# ansible-galaxy list -p ./roles/ | grep 'robertdebock.users'
- robertdebock.users, 5.4.0
```

## Output

```
# ansible-playbook playbook.yml -i inventories/redacted/ --vault-password-file ~/.vault_pass.txt
ERROR! this task 'ansible.builtin.import_tasks' has extra params, which is only allowed in the following modules: ansible.windows.win_command, shell, win_shell, include_vars, ansible.windows.win_shell, import_role, script, meta, include, include_tasks, group_by, raw, include_role, command, import_tasks, win_command, add_host, set_fact

The error appears to be in '/git/ansible/roles/robertdebock.users/tasks/main.yml': line 4, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: import assert.yml
  ^ here
```

vscode linter of extension Ansible v0.7.1 JSON Schema Ansible Tasks File on the main.yml (lines):

```
4 - name: import assert.yml
5   ansible.builtin.import_tasks: assert.yml
6   run_once: yes
7   delegate_to: localhost
```
4: `Missing property "action".yaml-schema: TaskModel | BeremothTaskModel`
5: `Property ansible.builtin.import_tasks is not allowed.yaml-schema: TaskModel`
6: `Incorrect type. Expected "boolean".yaml-schema: Run Once | BeremothTaskModel`

## Environment

- Control node OS: 18.04.6 LTS (Bionic Beaver)
- Control node Ansible version: 2.10.2
- Managed node OS: 20.04.2 LTS (Focal Fossa)
