### ISSUE TITLE
"msg": "groupdel: cannot remove the primary group of user

### ISSUE THREAD

**Issue by charnet1019** [robertdebock/ansible-role-users#25]
playbook:

```
---

- name: user mgr
  hosts: demo
  become: yes
  gather_facts: yes

  roles:
    - role: users
      users_user_list:
        - name: tim
          state: absent

      users_group_list:
        - name: tim
          state: absent
```

**Comment by robertdebock** [comment]
Acknowledged. This is caused by the order of calling the `group.yml` (first) and `users.yml` (second).

 I'm not sure how to resolve this exact situation. Keeping the issue open for future reference.

A work-around can be to first define the user to delete:

```yaml
- name: user mgr
  hosts: demo
  become: yes
  gather_facts: yes

  roles:
    - role: users
      users_user_list:
        - name: tim
          state: absent
```

Run ansible, and next run, define the group to delete:

```yaml
- name: user mgr
  hosts: demo
  become: yes
  gather_facts: yes

  roles:
    - role: users
      users_group_list:
        - name: tim
          state: absent
```
