### ISSUE TITLE
Allow private key to be given and placed on a machine.

### ISSUE THREAD

**Issue by robertdebock** [robertdebock/ansible-role-users#28]
## Proposed feature

It would be nice if this role can place a user-specified private key. Something like this:

```yaml
users_user_list:
  - name: privkeyuser
    private_keys:
      - name: id_rsa
        content: >
        -----BEGIN RSA PRIVATE KEY-----
        MIIEowxyz
        -----END RSA PRIVATE KEY-----
```

## Rationale

Provisioning a user with private key is user-friendly.

Please consider [sponsoring me](https://github.com/sponsors/robertdebock).
