### ISSUE TITLE
For root user wrong home directory is used

### ISSUE THREAD

**Issue by memoryleak** [robertdebock/ansible-role-users#29]
## Describe the bug

When using this role to set root user configurations, the wrong home directory is used: Keys are placed in /home/root instead of /root

## Playbook

```yaml
---
users_user_list:
    - name: root
      authorized_keys: "{{ authorized_keys }}"
      private_keys:
        - name: id_ed25519
          content: "{{ lookup('hashi_vault', 'secret=credentials/keys/machine:private') }}"
```
```yaml
---
- name: Bootstrap machines
  hosts: all
  roles:
    - name: robertdebock.core_dependencies
    - name: robertdebock.bootstrap
    - name: robertdebock.auto_update
    - name: robertdebock.locale
    - name: robertdebock.openssh
    - name: robertdebock.users
```
## Output

```bash
$ find /root/.ssh/
/root/.ssh/
/root/.ssh/authorized_keys
/root/.ssh/known_hosts

$ find /home/root/.ssh/
/home/root/.ssh/
/home/root/.ssh/id_ed25519
```

## Environment

Target: `Fedora release 38 (Thirty Eight)`
Role version: `5.5.0`
