### ISSUE TITLE
Error in "Ensure the sudoers.d directory is checked..." ?

### ISSUE THREAD

**Issue by luri-fr** [robertdebock/ansible-role-users#30]
## Describe the bug

Hi,
Ty for you're hard work.

I'm read you're code and, perhaps they have an mistake in tasks/user.yml near line 55 : 

```
- name: user | Ensure the sudoers.d directory is checked for user sudoers files (will be put after EOF if not exists)
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    line: "#includedir /etc/sudoers.d"
```

# is a comment, no ?
In my  /etc/sudoers file on an debian 11, i have `@includedir /etc/sudoers.d `

is this an mistake or not ?
