### ISSUE TITLE
Ansible group management

### ISSUE THREAD

**Issue by MaxiReglisse** [robertdebock/ansible-role-users#37]
Hello everyone

I'm trying to use the robertdebock.users role to create sudoers for my virtualization infrastructure, using the following principle: if the VM is in the "robert" Ansible group, then I create a "robert" account for it.
But the "ansible_group in group_names" condition is not taken into account and the account is created for all users. Certain tasks are avoided but, alas, account creations are carried out correctly.

Here is the role dedicated to this task:

```
# roles/users/tasks/sudoers.yml
- name: Include variables from sudoers.yml
  include_vars:
    file: "{{ role_path }}/defaults/sudoers.yml"
- name: Creation of Unix groups in a loop on the group dictionary
  include_role:
    name: robertdebock.users
  vars:
    name: "{{ group_item.name }}"
    system: "{{ group_item.system | default(false) }}"
    ansible_group: "{{ group_item.ansible_group }}"
  loop: "{{ users_groups }}"
  loop_control:
    loop_var: group_item
  when:
     - group_item.ansible_group is defined and group_item.ansible_group in group_names
- name: Create accounts in a loop on the user dictionary
  include_role:
    name: robertdebock.users
  vars:
    name: "{{ user_item.name }}"
    password: "{{ user_item.password }}"
    update_password: on_create
    group: "{{ user_item.group }}"
    sudo_options: "{{ user_item.sudo_options }}"
    ansible_group: "{{ user_item.ansible_group }}"
  loop: "{{ users }}"
  loop_control:
    loop_var: user_item
  when:
    - user_item is defined and user_item.ansible_group is defined and user_item.ansible_group in group_names
``` 

Below is a sample of my user data.
```
# roles/users/defaults/sudoers.yml
users_groups:
  - name: almina
    ansible_group: almina
  - name: chfalcon
    ansible_group: chfalcon

users:
  - name: almina
    comment: Marie-Almina Gindre
    group: almina
    password: "$6$9...TVg/"
    cron_allow: no
    sudo_options: "ALL=(ALL) NOPASSWD: ALL"
    ansible_group: almina

  - name: chfalcon
    comment: "Charles-Henri Falconnet"
    group: chfalcon
    password: "$y$j9...dNA"
    cron_allow: yes
    sudo_options: "ALL=(ALL) NOPASSWD: ALL"
    ansible_group: chfalcon
``` 

Extract from my_hosts showing that the VM is zuri is only a member of the Almina group
```
[almina]
zuri.inframshe.univ-fcomte.fr
[chfalcon]
``` 

Finally, here's the output of the playbook execution, in which we can see that one task has been skipped, while the others have been completed.

```
TASK [Create accounts in a loop on the user dictionary] ***********************************************************************************************************************************************************
skipping: [zuri.inframshe.univ-fcomte.fr] => (item={'name': 'chfalcon', 'comment': 'Charles-Henri Falconnet', 'group': 'chfalcon', 'password': '$y$j...dNA', 'cron_allow': True, 'sudo_options': 'ALL=(ALL) NOPASSWD: ALL', 'ansible_group': 'chfalcon'}) 

TASK [robertdebock.users : assert | Test users_ssh_key_directory] *************************************************************************************************************************************************
ok: [zuri.inframshe.univ-fcomte.fr -> localhost]

TASK [robertdebock.users : assert | Test users_shell] *************************************************************************************************************************************************************
ok: [zuri.inframshe.univ-fcomte.fr -> localhost]

TASK [robertdebock.users : assert | Test users_cron_allow] ********************************************************************************************************************************************************
ok: [zuri.inframshe.univ-fcomte.fr -> localhost]

TASK [robertdebock.users : assert | Test users_create_home] *******************************************************************************************************************************************************
ok: [zuri.inframshe.univ-fcomte.fr -> localhost]
``` 

I really don't see what the problem is.

Please note that if I use the ansible.builtin.group role, then the "when" clause is taken into account when creating groups. But that's not the case with robertdebock.users... and ansible.builtin.user doesn't exist yet.

Any help would be appreciated, thanks in advance.

Ernest.

**Comment by robertdebock** [comment]
You are setting variables `name` and `password`, that the role does not listen to. The role listens to `users`. Please see `molecule/default/converge.yml` for examples.

```yaml
name: Create accounts in a loop on the user dictionary
include_role:
  name: robertdebock.users
  vars:
    name: "{{ user_item.name }}"
    password: "{{ user_item.password }}"
    update_password: on_create
    group: "{{ user_item.group }}"
    sudo_options: "{{ user_item.sudo_options }}"
    ansible_group: "{{ user_item.ansible_group }}"
  loop: "{{ users }}"
  loop_control:
    loop_var: user_item
  when:
    - user_item is defined and user_item.ansible_group is defined and user_item.ansible_group in group_names`
```
