### ISSUE TITLE
Confirm/fix sudoers syntax

### ISSUE THREAD

**Issue by jkirk** [robertdebock/ansible-role-users#40]
I just reviewed the configuration and found this line:

https://github.com/robertdebock/ansible-role-users/blob/0775839ddef908c0bb66006761ec978e50547907/templates/sudo_group.j2#L4

According to the [sudoers(5)](https://manpages.debian.org/bookworm/sudo/sudoers.5.en.html) man page, a group is prefixed with a single '%' (see the section `Aliases` > `User ::=`).

Is that a typo or am I reading it wrong or does it mean something else?

I tried something like this:

```
  roles:
    - role: robertdebock.users
      users_groups:
        - name: mygroup
          sudo_options: ["ALL=NOPASSWD: ALL"]
      users:
        - name: 'myuser'
          group: mygroup
```

Which creates this `/etc/sudoers.d/mygroup`:
```
#                                                                                                        
# HEADER: managed by ansible, do NOT edit manually!                                                      
#                                                                                                        
%%mygroup ALL=NOPASSWD: ALL   
```

I don't think this is correct, or?

FTR, i worked around this, by using this line:
```
          sudo_options: "%mygroup ALL=NOPASSWD: ALL"
```
